LPS-168395 Changing the rendering of the LinkOurButton component as a button
liferay-usm/liferay-portal pull request #1010
Opened 2023-03-16 18:41 UTC by kildarep

Hello Reviewer!
Related Issue: https://issues.liferay.com/browse/LPS-168395

2023-03-16 18:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/5779/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5779/jenkins-report.html">here</a>.</b></p>

2023-03-16 18:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b66908c48b31ca2d3b4b27bdaa1981a741dc879b">b66908c48b31ca2d3b4b27bdaa1981a741dc879b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/kildarep/liferay-portal/tree/LPS-168395">LPS-168395</a><br/>Branch GIT ID: <a href="https://github.com/kildarep/liferay-portal/commit/bfdfc211a8f3f84436f0cdc3501221462bb1546d">bfdfc211a8f3f84436f0cdc3501221462bb1546d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5779/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5779/jenkins-report.html">here</a>.</h5></details></html>

2023-03-17 17:02 UTC, drewbrokke requested changes
Hey @kildarep, thank you for sending this change. I think it still needs some adjustment though, please see my inline comments.

Also, I suspect that the "activate" dropdown item found earlier in the `ViewFlatUsersManagementToolbarDisplayContext.java` file will have the same issue as this one. Would you be willing to check that as well? If it indeed does have the same issue then please apply the final fix there as well. It should end up being only a little more work since both dropdown items are referencing the same JS function.

Please let me know if you have any questions or concerns. Thanks!

2023-03-20 17:27 UTC, kildarep commented on modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/js/ViewFlatManagementToolbarPropsTransformer.js
> +};
Thanks for the Review @drewbrokke! 
 About your point about the **url**, both JavaScript and Java files use the url to send the request to the server to update user input. In JavaScript, the URL is passed to the `postForm` function, which sends a form via Ajax to the server. This is why the URL is passed as an argument in the function call.
In Java the url is defined as a string in a `DropdownItem` object. The url is added as a data attribute in the DropdownItem object and is passed to a JavaScript function called `deleteUsers`. The deleteUsers function is called with the url as an argument.
Both codes use the url to communicate with the server and update the user entries, but using different approaches to pass the URL and send the request so that it works and the Deactivate button does its job.

- Corrected ` action.es ` import

2023-04-25 19:25 UTC, brunofalc commented
Hey @kildarep @drewbrokke
Do we have updates about this?

2023-04-28 06:19 UTC, ethib137 commented
Hey @brunofalc I provided details for how this should be fixed in Slack [here](https://liferay.slack.com/archives/C04CPMRMXAL/p1678781386658369?thread_ts=1678732989.460219&cid=C04CPMRMXAL). I'll repost that here for context.

The main thing here is that if we want our html to be accessible we need to use the correct or “semantic” html for the purpose. So if a link is not actually linking to another page, it shouldn’t be a link, it should be a button. Aria should only be used if we can’t use the semantic html elements.

So we need to get LinkOrButton to render as a button. To do this, we simply need to not include an href, then it will render a button. But… now we need to find a way to still get our javascript to run when the button is clicked. The actionDropdownItems prop that is passed to <clay:management-toolbar> does NOT allow for onClick properties. Instead the <clay:management-toolbar> expects an onActionButtonClick prop that will handle onClick for all items. Normally this prop gets added by a propsTransformer.

Here is a propsTransformer [example](https://github.com/liferay/liferay-portal/blob/master/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/js/AccountEntriesManagementToolbarPropsTransformer.js#L73). You can see how it adds the onActionButtonClick prop. The AccountEntriesManagementToolbarPropsTransformer is passed to the <clay:management-toolbar> [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/view.jsp#L27).

So, dropdownItem.setHref() should never call javascript. It should only ever be passed a normal url. The Javascript should be moved to the onActionButtonClick prop that is added by a propsTransformer instead.

So we need to remove setHref throughout users-admin-web whenever it calls javascript, and move the javascript that is being called to a propsTransformer that is passed to the <clay:management-toolbar>.

It’s a bit more work than it initially appeared to be, but this will remove some technical debt and align with how <clay:management-toolbar> is being used throughout the rest of the portal.

@kildarep could you update the PR accordingly? Let me know if you have any questions or need any help.

2023-04-28 08:28 UTC, ethib137 commented
I'll finish up this PR. I want to apply these changes to the other actions that are still links so we solve this holistically. I'll send a follow up PR shortly.

2023-04-28 13:26 UTC, drewbrokke commented
@ethib137 will you please tag me in the resulting pull?

2023-04-28 17:18 UTC, kildarep commented
@ethib137 Could you tag me as well? I would like to see the final resolution of the problem

2023-05-02 11:56 UTC, brunofalc commented
ci:close

2023-05-02 11:56 UTC, closed without merging

2023-05-03 10:32 UTC, ethib137 commented
reopened here: https://github.com/liferay-usm/liferay-portal/pull/1038