LPS-180189 NoSuchUserException when adding PLO with liferay-online.properties configured after migrate from u62 to u69
liferay-usm/liferay-portal pull request #1028
Opened 2023-03-29 12:43 UTC by jgarcialr

2023-03-29 12:43 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-03-29 14:12 UTC, drewbrokke requested changes
@jgarcialr thank you for sending this change! I do have a concern though, please see my inline comment.

2023-03-29 14:12 UTC, drewbrokke commented on modules/apps/portal-language/portal-language-override-service/src/main/java/com/liferay/portal/language/override/service/impl/PLOEntryLocalServiceImpl.java
> +			ploEntry.setUserId(userId);
The call to `get` is intentional. What is the reason that an invalid `userId` is being passed in here? 

If we allow setting to an invalid `userId`, then we might just see this exception show up in a random spot elsewhere when they read this property expecting it to be valid.

2023-03-29 14:19 UTC, jgarcialr commented on modules/apps/portal-language/portal-language-override-service/src/main/java/com/liferay/portal/language/override/service/impl/PLOEntryLocalServiceImpl.java
> +			ploEntry.setUserId(userId);
Hi @drewbrokke ,

If the user is from a secondary company, when registering the objectdefinitions, there's a call made from objectDeployerImpl to addorUpdate a PLO.

As those users are not loaded yet, this request throws the NoSuchUserException despite the user existing in the database.

2023-03-29 14:46 UTC, jgarcialr commented
Hi @drewbrokke,

I think I can set the current companyId in threadlocal in objectdefinitiondeployer and it should work without this change.
Let me test it and I'll resend the PR to objects team.

2023-03-29 14:46 UTC, closed without merging

2023-03-29 14:51 UTC, jgarcialr commented
ci:stop

2023-03-29 14:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/3096/">test-portal-acceptance-pullrequest(master)#3096</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3096/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/1028">liferay-usm#1028</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2250351201">[master] ci:test:relevant - jgarcialr &gt; liferay-usm - PR#1028 - 2023-03-29[06:10:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/7122/">publish-testray-report#7122</a><br/></div></div>

2023-03-29 17:48 UTC, drewbrokke commented
@jgarcialr perhaps it would work to wrap these two calls? 
[ObjectDefinitionLocalServiceImpl.java#L476](https://github.com/drewbrokke/liferay-portal/blob/master/modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectDefinitionLocalServiceImpl.java?plain=1#L476)
[ObjectDefinitionLocalServiceImpl.java#L839](https://github.com/drewbrokke/liferay-portal/blob/master/modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectDefinitionLocalServiceImpl.java?plain=1#L839)

2023-03-30 07:22 UTC, jgarcialr commented
I did the change inside deploy method, I don't know if it's better to set it in there or at the point you advise to.

2023-03-30 13:47 UTC, drewbrokke commented
Either could work, but if it's possible that you'll run into this issue with some other service, then wrapping the calls to `deploy` would ensure that all implementations will happen inside the proper CompanyThreadLocal context.

Just my 2c