LPS-133375 The users.reminder.queries.enabled portal property should be configurable on the instance level
liferay-usm/liferay-portal pull request #127
Opened 2021-07-06 11:26 UTC by IstvanD

Dear Team,

I took this over from @balazsmatyassyliferay, and added the suggested changes from https://github.com/liferay-usm/liferay-portal/pull/66 and https://github.com/drewbrokke/liferay-portal/pull/1356. 

It is working now as expected, but I would like to ask your opinion on one part:

On the newly created _Instance Settings > User Authentication > Reminder Queries_ configuration page, in the last option's field ("Questions for user's password reminder queries.") we can see the language keys of the questions.

![config_page](https://user-images.githubusercontent.com/6039187/124590561-8e8e1b00-de5b-11eb-8e92-2ea659488bd5.png)

Is this OK, or should we rather present the translations (according to locale setting) of the questions instead of the language keys? I think if would be quite complex to implement, because on one hand, we would have to present the translations on the UI, and on the other, save the language keys as the actual data in the backend. Also, we would have to distinguish between the localizable default questions initially loaded as language keys from `portal.properties` and the non-localizable raw text questions added by the user.

Please let me know your thought about this matter.

Thank you and best regards,
István

2021-07-06 11:26 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-07-06 11:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2336/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/2336/jenkins-report.html">here</a>.</b></p>

2021-07-06 11:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f38f79ec048f97eaf7f4a17ea48673e4eaee99bf">f38f79ec048f97eaf7f4a17ea48673e4eaee99bf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/IstvanD/liferay-portal/tree/LPS-133375">LPS-133375</a><br/>Branch GIT ID: <a href="https://github.com/IstvanD/liferay-portal/commit/b792bece061034ec69cab687266d6fc06ff9f73c">b792bece061034ec69cab687266d6fc06ff9f73c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2336/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2336/jenkins-report.html">here</a>.</h5></details></html>

2021-07-06 11:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/2530/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2530/jenkins-report.html">here</a>.</b></p>

2021-07-06 11:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2336/">test-portal-source-format#2336</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2336/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/127">liferay-usm#127</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545180999">[master] ci:test:sf - IstvanD &gt; liferay-usm - PR#127 - 2021-07-06[04:26:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7052/">publish-testray-report#7052</a><br/></div></div>

2021-07-06 13:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 22 out of 23 jobs passed in 1 hour 57 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f38f79ec048f97eaf7f4a17ea48673e4eaee99bf">f38f79ec048f97eaf7f4a17ea48673e4eaee99bf</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f38f79ec048f97eaf7f4a17ea48673e4eaee99bf">f38f79ec048f97eaf7f4a17ea48673e4eaee99bf</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2075">Acceptance Upstream DXP (master) #2075</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14049/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475973/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465164/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475976/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14051/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14057/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475974/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14050/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14053/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 21 out of 23 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/2530/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14048/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14055/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476770/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14049/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465166/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465165/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14056/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475973/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475977/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14054/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465164/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476771/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475976/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14052/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475975/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14051/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475972/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14057/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475974/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476772/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14050/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14053/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2530/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at f38f79ec048f97eaf7f4a17ea48673e4eaee99bf:</strong></summary><ol><li><div><h5><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14048/">test-portal-acceptance-pullrequest-batch(ma [...]

2021-07-06 13:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/2530/">test-portal-acceptance-pullrequest(master)#2530</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2530/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/127">liferay-usm#127</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545215356">[master] ci:test:relevant - IstvanD &gt; liferay-usm - PR#127 - 2021-07-06[04:26:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7070/">publish-testray-report#7070</a><br/></div></div>

2021-07-06 17:45 UTC, drewbrokke commented
Hey @IstvanD, let's go for a compromise and do a `aui:select` field with `multiple` enabled. That way we can display the translated text, but the values would still be language key.s This would not allow the user to add their own questions, but I think that's ok considering there was not a UI for it before. Thoughts?

2021-07-07 12:26 UTC, IstvanD commented
Hi @drewbrokke 

Thank you for your quick reply!
I have checked your suggestion and indeed, the questions are shown in their correct translation in `aui:select`.
However, I have sadly discovered downsides to this approach as well. As you said, the user is not able to add their own questions. However, it is possible to add them in `portal-ext.properties`, like this:

```
    users.reminder.queries.questions=\
        what-is-your-primary-frequent-flyer-number,\
        what-is-your-library-card-number,\
        what-was-your-first-phone-number,\
        what-was-your-first-teacher's-name,\
        what-is-your-father's-middle-name,\
        Is this my first question?,\
        Is this my second question?
```
Also, the user may accidentally select only one question or not all questions from the list, and save the configuration. The questions that weren't selected would be lost and there would be no way to add them again.

So, as a second thought, maybe it would be fine for now to stick with the textarea solution. This would resemble the `portal-ext.properties` solution most closely. If the customer raises their concern with displaying the default questions as language keys, we could explain to them the merits of the current solution and the limitations of the alternatives If they insist, perhaps we would look for yet another solution that does not have limitations.

Do you agree with this plan?

Thank you and best regards,
István

2021-07-07 15:53 UTC, drewbrokke commented
Thanks for your reply and suggestions, @IstvanD! In regards to this concern:

> Also, the user may accidentally select only one question or not all questions from the list, and save the configuration. The questions that weren't selected would be lost and there would be no way to add them again.

Wouldn't it be possible to force reading the possible values for the multi-select from only `portal.properties` and not the company settings? That way it would not depend on what the user chose?

2021-07-07 15:56 UTC, drewbrokke commented
My other question is: How much of a priority is allowing adding custom questions via the UI? If it is imperative that we allow the user to add their own questions in the UI, then the multi-select is not an option whether we can get it to work or not.

2021-07-07 16:53 UTC, IstvanD commented
Hi @drewbrokke

> Wouldn't it be possible to force reading the possible values for the multi-select from only portal.properties and not the company settings? That way it would not depend on what the user chose. Thoughts?

The way it currently works is that the questions are loaded from portal.properties (or portal-ext.properties if it is overridden) for every virtual instance (company). As soon as the list is edited and saved from the configuration page, the values will be saved as portal properties. Physically, they'll stored in the `portalproperties` database table. If the user accesses the configuration page, the values will be loaded from the database. I think an average user would expect it to behave this way as well.

> How much of a priority is allowing adding custom questions via the UI? If it is imperative that we allow the user to add their own questions in the UI, then the multi-select is not an option whether we can get it to work or not.

I think we should go with the most intuitive and least surprising/disruptive way when moving this setting from text based to UI based. In portal(-ext).properties the user can add to the list, delete from the list, and edit the existing values in the list. With the textarea that is currently in the configuration page, the user can do all of that. If we would switch to a (multi) select list, an additional input field would be necessary for adding further questions.

2021-07-07 21:41 UTC, drewbrokke commented
@IstvanD that works for me, let's go with the text field. My only request is to add a detail into the help text that this list is comma-separated.

2021-07-08 08:27 UTC, IstvanD commented
Hi @drewbrokke 

I added in the help text that the list is comma-separated.

Best regards,
István

2021-07-08 20:21 UTC, drewbrokke requested changes
@IstvanD this is getting close. There are some adjustments needed in the language keys. Please see my inline comments.

2021-07-08 20:21 UTC, drewbrokke commented on modules/apps/portal-settings/portal-settings-web/src/main/resources/META-INF/resources/authentication/reminder_queries.jsp
> +	<aui:input helpMessage="users-password-reminder-queries-questions-help" label="users-password-reminder-queries-questions" name='<%= "settings--" + PropsKeys.USERS_REMINDER_QUERIES_QUESTIONS + "--" %
@IstvanD I think we should re-work these language keys to match the portal properties. Right now it seems like the words are being rearranged.

So for example, `PropsKeys.USERS_REMINDER_QUERIES_ENABLED` should have the lang keys: `users-reminder-queries-enabled` and `users-reminder-queries-enabled-help`. This will also have the benefit of grouping all the lang keys together in the `Language.properties` files.

2021-07-08 20:21 UTC, drewbrokke commented on modules/apps/portal-settings/portal-settings-lang/src/main/resources/content/Language.properties
> +display-users-password-reminder-queries-answer-in-plain-text=Display user's answer for password reminder queries in plain text.
In general, when using `user's` it should be either: `...a user's..` or `...the user's...`. 

But in this case, we can drop the reference to `user` and just say: `Display answers for password reminder queries in plain text.`

2021-07-08 20:21 UTC, drewbrokke commented on modules/apps/portal-settings/portal-settings-lang/src/main/resources/content/Language.properties
> +enable-users-password-reminder-queries-custom-question=Enable custom questions for user's password reminder queries.
Drop `user's` here as well.

2021-07-08 20:21 UTC, drewbrokke commented on modules/apps/portal-settings/portal-settings-lang/src/main/resources/content/Language.properties
> +enable-users-password-reminder-queries=Enable user's password reminder queries.
Drop `user's`

2021-07-08 20:21 UTC, drewbrokke commented on modules/apps/portal-settings/portal-settings-lang/src/main/resources/content/Language.properties
> +users-password-reminder-queries-questions=Questions for user's password reminder queries.
Drop `user's`

2021-07-08 20:21 UTC, drewbrokke commented on modules/apps/portal-settings/portal-settings-lang/src/main/resources/content/Language.properties
> +users-password-reminder-queries-questions-help=Comma-separated list of questions for user's password reminder queries.
-> `A comma-separated list of questions used as password reminder queries`.

2021-07-08 20:21 UTC, drewbrokke commented on modules/apps/portal-settings/portal-settings-lang/src/main/resources/content/Language.properties
> +enable-users-password-reminder-queries-help=Enable users to use password reminder queries.
-> `Enable password reminder queries to be used when recovering a user's password.`

2021-07-09 11:15 UTC, IstvanD commented
Hi @drewbrokke 

I implemented your suggestions and pushed them.

2021-07-09 15:33 UTC, drewbrokke commented
Thanks @IstvanD! See https://github.com/liferay-usm/liferay-portal/pull/140

2021-07-09 15:33 UTC, closed without merging

2021-07-09 15:34 UTC, drewbrokke commented
@IstvanD I spent a little more time looking at the language keys. I went ahead and updated them so you wouldn't be blocked any further by me.