LPS-134922 Add API to get or set current account entry
liferay-usm/liferay-portal pull request #219
Opened 2021-08-17 22:17 UTC by pei-jung

2021-08-17 22:18 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-08-17 22:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/527/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-source-format/builds/527/jenkins-report.html">here</a>.</b></p>

2021-08-17 22:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/603/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/603/jenkins-report.html">here</a>.</b></p>

2021-08-17 22:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a4e6ca098566e12cd033072c7e5326a3bbe5ae8b">a4e6ca098566e12cd033072c7e5326a3bbe5ae8b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pei-jung/liferay-portal/tree/LPS-134922">LPS-134922</a><br/>Branch GIT ID: <a href="https://github.com/pei-jung/liferay-portal/commit/02bed1d5141d5d6ab48257ae6615d95499b33486">02bed1d5141d5d6ab48257ae6615d95499b33486</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/527/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/527/jenkins-report.html">here</a>.</h5></details></html>

2021-08-17 22:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/527/">test-portal-source-format#527</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/527/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/219">liferay-usm#219</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1554056654">[master] ci:test:sf - pei-jung &gt; liferay-usm - PR#219 - 2021-08-17[15:18:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/1674/">publish-testray-report#1674</a><br/></div></div>

2021-08-17 22:25 UTC, pei-jung commented
@drewbrokke I didn't include the [account type check ](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/commerce-account-service/src/main/java/com/liferay/commerce/account/internal/util/CommerceAccountHelperImpl.java#L205-L226)in the API because I'm not sure if we'll be supporting the commerce site types in our API.

2021-08-17 23:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 10 out of 10 jobs passed</h3><h3>:x: ci:test:relevant - 19 out of 22 jobs passed in 1 hour 39 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a4e6ca098566e12cd033072c7e5326a3bbe5ae8b">a4e6ca098566e12cd033072c7e5326a3bbe5ae8b</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a4e6ca098566e12cd033072c7e5326a3bbe5ae8b">a4e6ca098566e12cd033072c7e5326a3bbe5ae8b</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2224">Acceptance Upstream DXP (master) #2224</a></p><details><summary><strong>ci:test:stable - 10 out of 10 jobs PASSED</strong></summary><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2533/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3940/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2537/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28910/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2536/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28911/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3895/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2539/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2534/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3896/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 19 out of 22 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/603/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3898/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</strong></strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2538/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>19 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2540/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2533/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3942/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3940/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2542/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3897/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2537/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2541/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28910/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3941/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2536/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2535/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28911/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3895/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2539/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3899/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2534/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2532/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3896/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/603/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2538/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></h5><div><h6>Job Results:</h6><p>3 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/2 [...]

2021-08-18 00:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/603/">test-portal-acceptance-pullrequest(master)#603</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/603/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/219">liferay-usm#219</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1554070791">[master] ci:test:relevant - pei-jung &gt; liferay-usm - PR#219 - 2021-08-17[15:18:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/1678/">publish-testray-report#1678</a><br/></div></div>

2021-08-18 04:22 UTC, Sharryxue commented
- modules-semantic-versioning-jdk8/0/0 failure seems need additional fix, refer [console], hello @pei-jung, would you please help with double check? Thanks. 
(https://testray.liferay.com/reports/production/logs/2021-08/test-1-28/test-portal-acceptance-pullrequest(master)/603/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz)
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/account/account-api] STARTED
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/account/account-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.account.constants                      MINOR      1.6.0      1.6.0      1.7.0      VERSION INCREASE REQUIRED
     [exec]     	+   class      com.liferay.account.constants.AccountWebKeys
     [exec]     		+   field      CURRENT_ACCOUNT_ENTRY_ID
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   LIFERAY_SHARED_CURRENT_ACCOUNT_ENTRY_ID
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     <init>()
     [exec]     			+   return     void
     [exec]     		+   method     clone()
     [exec]     			+   access     protected
     [exec]     			+   return     java.lang.Object
     [exec]     		+   method     equals(java.lang.Object)
     [exec]     			+   return     boolean
     [exec]     		+   method     finalize()
     [exec]     			+   access     protected
     [exec]     			+   return     void
     [exec]     		+   method     hashCode()
     [exec]     			+   return     int
     [exec]     		+   method     toString()
     [exec]     			+   return     java.lang.String
     [exec]         at org.junit.Assert.fail(Assert.java:89)
```

2021-08-18 15:23 UTC, drewbrokke requested changes

2021-08-18 15:23 UTC, drewbrokke commented on modules/apps/account/account-api/src/main/java/com/liferay/account/manager/AccountSessionManager.java
> +public interface AccountSessionManager {
So it's not guaranteed that we will always tie the current account to the session. That is an implementation detail that could change based on requirements. I would consider this more like a `CurrentAccountEntryHelper` or something similar

2021-08-18 15:23 UTC, drewbrokke commented on modules/apps/account/account-service/src/main/java/com/liferay/account/internal/manager/AccountSessionManagerImpl.java
> +		HttpServletRequest httpServletRequest) {
So if we're not going to actually use `groupId`, we should not include it here. I know that Commerce uses it for validation, so let's let them keep doing that and then call our API after validation. If it becomes necessary in the future, we can expand this API to include group scoping the current account.

2021-08-18 15:58 UTC, pei-jung commented on modules/apps/account/account-api/src/main/java/com/liferay/account/manager/AccountSessionManager.java
> +public interface AccountSessionManager {
I struggle with the naming because in order to use `HttpServletRequest` in the API, it needs to meet the criteria defined in [JavaAPISignatureCheck](https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/java_api_signature_check.markdown)

2021-08-18 16:01 UTC, pei-jung commented on modules/apps/account/account-service/src/main/java/com/liferay/account/internal/manager/AccountSessionManagerImpl.java
> +		HttpServletRequest httpServletRequest) {
Currently, the `groupId` is used to scope the current account entry id by site. Do we not want to include that?

2021-08-18 16:03 UTC, drewbrokke commented on modules/apps/account/account-api/src/main/java/com/liferay/account/manager/AccountSessionManager.java
> +public interface AccountSessionManager {
Is it reasonable to receive a `portletRequest` instead?

2021-08-18 16:07 UTC, drewbrokke commented on modules/apps/account/account-api/src/main/java/com/liferay/account/manager/AccountSessionManager.java
> +public interface AccountSessionManager {
They are suppressing that check: https://github.com/liferay/liferay-portal/blob/a4e6ca098566e12cd033072c7e5326a3bbe5ae8b/modules/apps/commerce/source-formatter-suppressions.xml#L20

2021-08-18 16:08 UTC, pei-jung commented on modules/apps/account/account-api/src/main/java/com/liferay/account/manager/AccountSessionManager.java
> +public interface AccountSessionManager {
Ok, `portletRequest` can work. We can use `Portal` to get the `HttpServletRequest`

2021-08-18 16:13 UTC, drewbrokke commented on modules/apps/account/account-api/src/main/java/com/liferay/account/manager/AccountSessionManager.java
> +public interface AccountSessionManager {
We also have access to `PortalSessionThreadLocal.getHttpSession` here. It gets set in the `MainServlet`, so it should be pretty reliable. If that works, we might be able to not even require a request at all.

2021-08-18 16:17 UTC, drewbrokke commented on modules/apps/account/account-api/src/main/java/com/liferay/account/manager/AccountSessionManager.java
> +public interface AccountSessionManager {
Also, if we _do_ remove the request, we will need to require a `userId`.

2021-08-18 20:31 UTC, closed without merging