LPS-125328
liferay-usm/liferay-portal pull request #30
Opened 2021-05-14 21:32 UTC by brunoquei2105

2021-05-14 21:32 UTC, liferay-continuous-integration commented
Your pull request was not tested because you are not a member of the Liferay organization. Please make sure that you have been added and that your organization membership is set as Public. See https://help.github.com/articles/publicizing-or-hiding-organization-membership for more information.

2021-05-14 21:32 UTC, liferay-continuous-integration commented
Your pull request was not tested because you are not a member of the Liferay organization. Please make sure that you have been added and that your organization membership is set as Public. See https://help.github.com/articles/publicizing-or-hiding-organization-membership for more information.

2021-05-17 22:52 UTC, drewbrokke requested changes
@brunoquei2105 this is a good start. The field `maxlength` works correctly now.

There are a couple of problems that you'll need to address now:
1. Since you changed the `name` attribute on the field, the UI label changed. See my inline comment.
2. The phone number does not save now. Whenever you change a field name, you need to make sure that it is handled properly when the form is saved, and that it displays properly in the UI. Right now, I think both reading and writing are broken. You'll want to look at the `portlet:actionURL` tag on the `edit_account_entry_address.jsp` to see which action is being performed when this form is submitted.

Please update with these changes and resend. Feel free to ping me if you have any questions. Thanks!

2021-05-17 22:52 UTC, drewbrokke commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/edit_account_entry_address.jsp
> +		<aui:input name="number" />
I just learned that the `aui:input` tag also has a `model` attribute! So instead of adding the `model-context` tag above, we can just pass in `Phone.class` to the `model` attribute of `aui:input`. Much more concise!

2021-05-17 22:52 UTC, drewbrokke commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/edit_account_entry_address.jsp
> +		<aui:input name="number" />
Since you're changing the field name, you'll need to make sure that the input has the same label in the UI. `aui:input` has a `label` attribute you can use.

2021-05-17 22:52 UTC, closed without merging

2021-05-17 23:22 UTC, brunoquei2105 commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/edit_account_entry_address.jsp
> +		<aui:input name="number" />
Got it!