LPS-156222 | master
liferay-usm/liferay-portal pull request #654
Opened 2022-07-18 06:38 UTC by sontruongces

Hi team,
This PR is the fix for the [LPS-156222](https://issues.liferay.com/browse/LPS-156222), the original has passed my review at sontruonces#20. Please help me review it and give me feedback.
Thanks!
cc: @locpham97

2022-07-18 06:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-07-18 06:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3703/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3703/jenkins-report.html">here</a>.</b></p>

2022-07-18 06:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/2195/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2195/jenkins-report.html">here</a>.</b></p>

2022-07-18 06:41 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sontruongces/liferay-portal/tree/LPS-156222-master">LPS-156222-master</a><br/>Branch GIT ID: <a href="https://github.com/sontruongces/liferay-portal/commit/47e92b6882c5d34d810bb8317b286f559d9cf70d">47e92b6882c5d34d810bb8317b286f559d9cf70d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2195/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2195/jenkins-report.html">here</a>.</h5></details></html>

2022-07-18 06:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2195/">test-portal-source-format#2195</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2195/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/654">liferay-usm#654</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1909770743">[master] ci:test:sf - sontruongces &gt; liferay-usm - PR#654 - 2022-07-17[23:39:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/8335/">publish-testray-report#8335</a><br/></div></div>

2022-07-18 08:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3703/">test-portal-acceptance-pullrequest(master)#3703</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3703/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/654">liferay-usm#654</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1909788213">[master] ci:test:relevant - sontruongces &gt; liferay-usm - PR#654 - 2022-07-17[23:39:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9614/">publish-testray-report#9614</a><br/></div></div>

2022-07-27 09:07 UTC, sontruongces commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/java/com/liferay/dynamic/data/mapping/form/field/type/internal/localizable/text/LocalizableTextDDMFormFieldValueAccessor.java
> +				jsonObject.get(LanguageUtil.getLanguageId(locale)))) {
@drewbrokke, the fix was updated based on your comment. Thanks!

2022-07-27 13:38 UTC, drewbrokke requested changes
@locpham97 overall this looks good. However, we also need to add test coverage for this scenario. Can you please include an assertion inside of [LocalizableTextDDMFormFieldValueAccessorTest.java](https://github.com/drewbrokke/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/test/java/com/liferay/dynamic/data/mapping/form/field/type/internal/localizable/text/LocalizableTextDDMFormFieldValueAccessorTest.java#L69-L81)? Thank you!

2022-07-27 13:38 UTC, drewbrokke commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/java/com/liferay/dynamic/data/mapping/form/field/type/internal/localizable/text/LocalizableTextDDMFormFieldValueAccessor.java
> +		for (String key : jsonObjectKeys) {
SF: Inline the `jsonObjectKeys` variable.

2022-08-03 04:40 UTC, sontruongces commented
@drewbrokke , the fix was SF-ed and added test by @locpham97. Thanks!

2022-08-04 16:20 UTC, drewbrokke commented
See https://github.com/liferay-forms/liferay-portal/pull/1896. Thanks!

2022-08-04 16:20 UTC, closed without merging