LPS-147372 Add itemsTotal for different pages in Users Admin
liferay-usm/liferay-portal pull request #659
Opened 2022-07-20 22:02 UTC by murilostodolni

2022-07-20 22:02 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-07-20 22:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/22411abd9875742b0d5eeb0c54ea8f94c0741166">22411abd9875742b0d5eeb0c54ea8f94c0741166</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/murilostodolni/liferay-portal/tree/LPS-147372">LPS-147372</a><br/>Branch GIT ID: <a href="https://github.com/murilostodolni/liferay-portal/commit/101a388c3327512ed472efe4fe44d4372d0e352f">101a388c3327512ed472efe4fe44d4372d0e352f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2859/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2859/jenkins-report.html">here</a>.</h5></details></html>

2022-07-20 22:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2859/">test-portal-source-format#2859</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2859/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/659">liferay-usm#659</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1912681639">[master] ci:test:sf - murilostodolni &gt; liferay-usm - PR#659 - 2022-07-20[15:02:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/10447/">publish-testray-report#10447</a><br/></div></div>

2022-07-20 22:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 10 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/22411abd9875742b0d5eeb0c54ea8f94c0741166">22411abd9875742b0d5eeb0c54ea8f94c0741166</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/22411abd9875742b0d5eeb0c54ea8f94c0741166">22411abd9875742b0d5eeb0c54ea8f94c0741166</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3577">Acceptance Upstream DXP (master) #3577</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/2442/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2442/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/2442/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] * Where:
     [exec] Build file '/opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/build.gradle' line: 113
     [exec] 
     [exec] * What went wrong:
     [exec] A problem occurred evaluating project ':dxp:apps:osb:osb-site-initializer:osb-site-initializer-customer-portal'.
     [exec] &gt; Could not resolve all files for configuration ':dxp:apps:osb:osb-site-initializer:osb-site-initializer-customer-portal:extraRemoteApp'.
     [exec]    &gt; Could not resolve com.liferay:com.liferay.osb.site.initializer.customer.portal.extra.remote.app:20220715.1659.
     [exec]      Required by:
     [exec]          project :dxp:apps:osb:osb-site-initializer:osb-site-initializer-customer-portal
     [exec]       &gt; Could not resolve com.liferay:com.liferay.osb.site.initializer.customer.portal.extra.remote.app:20220715.1659.
     [exec]          &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.osb.site.initializer.customer.portal.extra.remote.app/20220715.1659/com.liferay.osb.site.initializer.customer.portal.extra.remote.app-20220715.1659.pom'.
     [exec]             &gt; Could not GET 'https://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.osb.site.initializer.customer.portal.extra.remote.app/20220715.1659/com.liferay.osb.site.initializer.customer.portal.extra.remote.app-20220715.1659.pom'. Received status code 401 from server: Unauthorized
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':dxp:apps:osb:osb-site-initializer:osb-site-initializer-customer-portal'.
     [exec]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory\$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
     [exec]   at org.gradle.configuration.DefaultScriptPluginFactory\$ScriptPluginImpl.lambda\$apply\$0(DefaultScriptPluginFactory.java:133)
     [exec]   at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
     [exec]   at org.gradle.configuration.DefaultScriptPluginFactory\$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-07-20 22:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/2442/">test-portal-acceptance-pullrequest(master)#2442</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2442/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/659">liferay-usm#659</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1912683375">[master] ci:test:relevant - murilostodolni &gt; liferay-usm - PR#659 - 2022-07-20[15:02:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/5608/">publish-testray-report#5608</a><br/></div></div>

2022-07-21 00:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3766/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3766/jenkins-report.html">here</a>.</b></p>

2022-07-21 00:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/22411abd9875742b0d5eeb0c54ea8f94c0741166">22411abd9875742b0d5eeb0c54ea8f94c0741166</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/22411abd9875742b0d5eeb0c54ea8f94c0741166">22411abd9875742b0d5eeb0c54ea8f94c0741166</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3577">Acceptance Upstream DXP (master) #3577</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3766/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3766/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3766/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] * Where:
     [exec] Build file '/opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/build.gradle' line: 113
     [exec] 
     [exec] * What went wrong:
     [exec] A problem occurred evaluating project ':dxp:apps:osb:osb-site-initializer:osb-site-initializer-customer-portal'.
     [exec] &gt; Could not resolve all files for configuration ':dxp:apps:osb:osb-site-initializer:osb-site-initializer-customer-portal:extraRemoteApp'.
     [exec]    &gt; Could not resolve com.liferay:com.liferay.osb.site.initializer.customer.portal.extra.remote.app:20220715.1659.
     [exec]      Required by:
     [exec]          project :dxp:apps:osb:osb-site-initializer:osb-site-initializer-customer-portal
     [exec]       &gt; Could not resolve com.liferay:com.liferay.osb.site.initializer.customer.portal.extra.remote.app:20220715.1659.
     [exec]          &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.osb.site.initializer.customer.portal.extra.remote.app/20220715.1659/com.liferay.osb.site.initializer.customer.portal.extra.remote.app-20220715.1659.pom'.
     [exec]             &gt; Could not GET 'https://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.osb.site.initializer.customer.portal.extra.remote.app/20220715.1659/com.liferay.osb.site.initializer.customer.portal.extra.remote.app-20220715.1659.pom'. Received status code 401 from server: Unauthorized
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':dxp:apps:osb:osb-site-initializer:osb-site-initializer-customer-portal'.
     [exec]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory\$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
     [exec]   at org.gradle.configuration.DefaultScriptPluginFactory\$ScriptPluginImpl.lambda\$apply\$0(DefaultScriptPluginFactory.java:133)
     [exec]   at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
     [exec]   at org.gradle.configuration.DefaultScriptPluginFactory\$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-07-21 01:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3766/">test-portal-acceptance-pullrequest(master)#3766</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3766/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/659">liferay-usm#659</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1912794153">[master] ci:test:relevant - murilostodolni &gt; liferay-usm - PR#659 - 2022-07-20[17:49:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9737/">publish-testray-report#9737</a><br/></div></div>

2022-07-21 11:24 UTC, murilostodolni commented
ci:test:relevant

2022-07-21 11:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3596/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3596/jenkins-report.html">here</a>.</b></p>

2022-07-21 12:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 53 out of 54 jobs passed in 1 hour 20 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/22411abd9875742b0d5eeb0c54ea8f94c0741166">22411abd9875742b0d5eeb0c54ea8f94c0741166</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/22411abd9875742b0d5eeb0c54ea8f94c0741166">22411abd9875742b0d5eeb0c54ea8f94c0741166</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3577">Acceptance Upstream DXP (master) #3577</a></p><details><summary><strong>ci:test:stable - 26 out of 26 jobs PASSED</strong></summary><details><summary><strong>26 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49092/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131056/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131169/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116417/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131171/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127626/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116418/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109512/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49786/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132539/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116420/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127627/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/113774/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131053/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96088/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131172/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131054/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109514/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/71116/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131055/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127629/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/113776/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133546/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116421/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/58704/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127628/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 52 out of 54 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3596/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96090/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>52 Successful Jobs:</strong></summary><ul><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96089/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114977/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49416/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49092/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132538/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/114978/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132540/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49417/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133550/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131173/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/131057/">functional-tomcat90-mysql57-jdk8/0/5</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-10.li [...]

2022-07-21 12:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3596/">test-portal-acceptance-pullrequest(master)#3596</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3596/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/659">liferay-usm#659</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1913157624">[master] ci:test:relevant - murilostodolni &gt; liferay-usm - PR#659 - 2022-07-21[04:24:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/8517/">publish-testray-report#8517</a><br/></div></div>

2022-07-21 16:44 UTC, RafaelCRC requested changes
Hi @murilostodolni, your PR is missing the fix to add multiple items in different pages ***if you take account of account group pagination***, besides that, i think we need a little bit of a clarification about how it suppose to behave, is the counter max value above supposed to save the number of users in that current page or the total of available users? in conclusion, taking the example of account group, the real problem here is finding a way to save all selected users regardless of page. what do you think @drewbrokke

2022-07-25 19:49 UTC, murilostodolni commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp
> +	itemsTotal="<%= accountEntryDisplaySearchContainer.getResultEnd() - accountEntryDisplaySearchContainer.getStart() %>"
hi @drewbrokke the `selectAccountEntryManagementToolbarDisplayContext` haven't a method to return the total items in the current page. So, i did this subtraction for get the total items in the current page.

2022-07-25 20:20 UTC, drewbrokke commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp
> +	itemsTotal="<%= accountEntryDisplaySearchContainer.getResultEnd() - accountEntryDisplaySearchContainer.getStart() %>"
@murilostodolni take a look at the inheritance chain for SelectAccountEntryManagementToolbarDisplayContext:

```
SelectAccountEntryManagementToolbarDisplayContext extends
ViewAccountEntriesManagementToolbarDisplayContext extends
SearchContainerManagementToolbarDisplayContext extends
BaseManagementToolbarDisplayContext implements
ManagementToolbarDisplayContext
```

Any class that implements `ManagementToolbarDisplayContext` has a [default implementation of `getItemsTotal`](https://github.com/liferay/liferay-portal/blob/aabc2f3ad7b8f11b3dcb9e8325a27ff51eaa3268/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/display/context/ManagementToolbarDisplayContext.java#L85).

Also, `SearchContainerManagementToolbarDisplayContext` contains [an overridden implementation of that method](https://github.com/liferay/liferay-portal/blob/db47da1f26256ca919751566cb637814d3097b79/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/display/context/SearchContainerManagementToolbarDisplayContext.java#L61-L64) that returns the total from the `searchContainer`. 

In this case, if needed you can override it again inside of `SelectAccountEntryManagementToolbarDisplayContext` and place your logic inside there.

Does that seem clear? Please let me know if you have any other questions. Thanks!

2022-07-25 20:21 UTC, drewbrokke commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp
> +	itemsTotal="<%= accountEntryDisplaySearchContainer.getResultEnd() - accountEntryDisplaySearchContainer.getStart() %>"
Another thought is that since the `SearchContainerManagementToolbarDisplayContext` class just displays whatever total is present on the `searchContainer` object, you could also change where the total is set _to_ the `searchContainer`. In the end this is probably the better option.

2022-07-25 21:22 UTC, murilostodolni commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp
> +	itemsTotal="<%= accountEntryDisplaySearchContainer.getResultEnd() - accountEntryDisplaySearchContainer.getStart() %>"
Hi @drewbrokke sorry, i did see the inheritance chain. One question, if we change the `getItensTotal` in `SearchContainerManagementToolbarDisplayContext` for
```
@Override
	public int getItemsTotal() {
		return searchContainer.getResultEnd() - searchContainer.getStart();
	}
```
all the components using this method will change your comportament. Right? Is it the right thing to do? Because this bug only occurs on popup.

2022-07-25 21:31 UTC, drewbrokke commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp
> +	itemsTotal="<%= accountEntryDisplaySearchContainer.getResultEnd() - accountEntryDisplaySearchContainer.getStart() %>"
Correct, do not change the method in `SearchContainerManagementToolbarDisplayContext`. You would want to override the method in `SelectAccountEntryManagementToolbarDisplayContext`.

2022-07-25 21:40 UTC, murilostodolni commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp
> +	itemsTotal="<%= accountEntryDisplaySearchContainer.getResultEnd() - accountEntryDisplaySearchContainer.getStart() %>"
Perfect! Now, i understand. Thanks so much @drewbrokke

2022-07-25 21:53 UTC, drewbrokke commented on modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp
> +	itemsTotal="<%= accountEntryDisplaySearchContainer.getResultEnd() - accountEntryDisplaySearchContainer.getStart() %>"
Great! Anytime :)

2022-07-25 22:00 UTC, murilostodolni commented
ci:reopen

2022-07-25 22:01 UTC, murilostodolni commented
ci:test:sf

2022-07-25 22:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/2302/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2302/jenkins-report.html">here</a>.</b></p>

2022-07-25 22:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/be360bfe61eddcb9780dd6dc3f127d4138f91a47">be360bfe61eddcb9780dd6dc3f127d4138f91a47</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/murilostodolni/liferay-portal/tree/LPS-147372">LPS-147372</a><br/>Branch GIT ID: <a href="https://github.com/murilostodolni/liferay-portal/commit/fc682151603993fa3ea30adb9542ea0e6fe61bde">fc682151603993fa3ea30adb9542ea0e6fe61bde</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2302/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2302/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/account/account-admin-web/src/main/java/com/liferay/account/admin/web/internal/display/context/SelectAccountEntryManagementToolbarDisplayContext.java expected:&lt;...iner.getStart();
     [java]   \}
     [java] []
     [java]   @Override
     [java]   public ...&gt; but was:&lt;...iner.getStart();
     [java]   \}
     [java] [  ]
     [java]   @Override
     [java]   public ...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 1:00.755 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-37/job/test-portal-source-format/2302//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220725150409536.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220725150409536.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1801509830.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null2101529658
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 167ms
[junitreport] Deleting: /tmp/null2101529658
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 07-25-2022 15:04:11:516 PDT</pre></details></html>

2022-07-25 22:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2302/">test-portal-source-format#2302</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2302/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/659">liferay-usm#659</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1916672468">[master] ci:test:sf - murilostodolni &gt; liferay-usm - PR#659 - 2022-07-25[15:01:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/8722/">publish-testray-report#8722</a><br/></div></div>

2022-07-25 22:08 UTC, murilostodolni commented
ci:test:sf

2022-07-25 22:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/3132/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/3132/jenkins-report.html">here</a>.</b></p>

2022-07-25 22:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/be360bfe61eddcb9780dd6dc3f127d4138f91a47">be360bfe61eddcb9780dd6dc3f127d4138f91a47</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/murilostodolni/liferay-portal/tree/LPS-147372">LPS-147372</a><br/>Branch GIT ID: <a href="https://github.com/murilostodolni/liferay-portal/commit/ec84074ddc79ea5a7126fe8f8caeb216b07e4c2e">ec84074ddc79ea5a7126fe8f8caeb216b07e4c2e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/3132/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/3132/jenkins-report.html">here</a>.</h5></details></html>

2022-07-25 22:13 UTC, murilostodolni commented
ci:test:relevant

2022-07-25 22:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/3132/">test-portal-source-format#3132</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/3132/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/659">liferay-usm#659</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1916673212">[master] ci:test:sf - murilostodolni &gt; liferay-usm - PR#659 - 2022-07-25[15:09:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/11674/">publish-testray-report#11674</a><br/></div></div>

2022-07-25 22:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3676/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3676/jenkins-report.html">here</a>.</b></p>

2022-07-25 22:52 UTC, drewbrokke requested changes

2022-07-25 22:52 UTC, drewbrokke commented on modules/apps/account/account-admin-web/src/main/java/com/liferay/account/admin/web/internal/display/context/SelectAccountEntryManagementToolbarDisplayContext.java
> +	}
They question I have with this situation is, why is the `getTotal` value not correct in the first place? We have control over setting the total on to the SearchContainer, so if it's not right we should fix it where we set it. Make sense?

2022-07-25 23:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 25 out of 26 jobs passed</h3><h3>:x: ci:test:relevant - 49 out of 54 jobs passed in 1 hour 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/be360bfe61eddcb9780dd6dc3f127d4138f91a47">be360bfe61eddcb9780dd6dc3f127d4138f91a47</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/be360bfe61eddcb9780dd6dc3f127d4138f91a47">be360bfe61eddcb9780dd6dc3f127d4138f91a47</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1916676518">EE Development Acceptance (master) - 3592 - 2022-07-25[12:43:35]</a></p><details><summary><strong>ci:test:stable - 25 out of 26 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140248/"><strike>portal-license-smoke-jdk8/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>25 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130160/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130159/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/146494/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133976/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140251/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133977/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/138353/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133979/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140254/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/138355/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133980/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134584/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/138354/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/138351/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/146492/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140253/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133978/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134589/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/138359/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/138092/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140889/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/146497/">pmd-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/138358/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/146493/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/138356/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 49 out of 54 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3676/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130162/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140258/"><strike>functional-tomcat90-mysql57-jdk8/0/4</strike></a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140248/"><strike>portal-license-smoke-jdk8/0/0</strike></a></li></ul></li><li>semantic-versioning-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134586/"><strike>semantic-versioning-jdk8/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>49 Successful Jobs:</strong></summary><ul><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/133981/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140255/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134585/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130160/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134583/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134588/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/146496/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="htt [...]

2022-07-25 23:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3676/">test-portal-acceptance-pullrequest(master)#3676</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3676/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/659">liferay-usm#659</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1916754395">[master] ci:test:relevant - murilostodolni &gt; liferay-usm - PR#659 - 2022-07-25[15:14:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/8726/">publish-testray-report#8726</a><br/></div></div>

2022-07-26 17:24 UTC, murilostodolni commented on modules/apps/account/account-admin-web/src/main/java/com/liferay/account/admin/web/internal/display/context/SelectAccountEntryManagementToolbarDisplayContext.java
> +	}
Hi @drewbrokke 

So, the problem is when we paginated list. The total is not show the total in current page. See video without the method that i created:


https://user-images.githubusercontent.com/48572495/181070759-df7ca2d1-cb0e-46a8-bdb1-e4d582e236da.mp4

When we add the method that return the total in the current page (`searchContainer.getResultEnd() - searchContainer.getStart();`), the behavior is this:

https://user-images.githubusercontent.com/48572495/181071028-e050c47a-66a0-4d71-9726-23decab6a55f.mp4

Do you understand the problem that i see? Thank you

2022-07-26 17:38 UTC, RafaelCRC commented on modules/apps/account/account-admin-web/src/main/java/com/liferay/account/admin/web/internal/display/context/SelectAccountEntryManagementToolbarDisplayContext.java
> +	}
@murilostodolni i think the issue you're seeing there is a expected behavior, in this case we don't wanna see the total of items in a page, but the actual total of items. As i said before, if we compare with account group, the real issue is to preserve the selected items as we change pages.
I'll give you a example, i have 4 items separated in pages of 2, if i select the 2 of the first page and 1 of the second page, with your method (if pagination worked) i would see 3 of 2 selected. incorrect, do you agree?

2022-08-05 19:54 UTC, drewbrokke commented
@murilostodolni @RafaelCRC any updates on this one? Any blockers?

2022-08-09 18:04 UTC, murilostodolni commented
Hi @drewbrokke i don't have new updates. I will closed this PR and will open a new when has update. Thanks

2022-08-09 18:05 UTC, murilostodolni commented
ci:close

2022-08-09 18:05 UTC, closed without merging