LPS-159181 Cannot add widget to the User's page when manage pages
liferay-usm/liferay-portal pull request #670
Opened 2022-07-28 21:07 UTC by pei-jung

2022-07-28 21:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-07-28 21:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/1870/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1870/jenkins-report.html">here</a>.</b></p>

2022-07-28 21:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0fd9367fc83b9ec1b6e8f5c604bb96a223261fa5">0fd9367fc83b9ec1b6e8f5c604bb96a223261fa5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pei-jung/liferay-portal/tree/LPS-159181">LPS-159181</a><br/>Branch GIT ID: <a href="https://github.com/pei-jung/liferay-portal/commit/a0368accb846a1d89a6a87116e85afaefd8f0273">a0368accb846a1d89a6a87116e85afaefd8f0273</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1870/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1870/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-impl/src/com/liferay/portal/events/ServicePreAction.java expected:&lt;...letRequest =
     [java]               [PortalUtil.getOriginalServletRequest(
     [java]                 httpServletRequest);
     [java] 
     [java]             Map&lt;String, String[]&gt; parameterMap = new HashMap&lt;&gt;(
     [java]               originalHttpServletRequest.getParameterMap());
     [java] 
     [java]             parameterMap.remove("p_l_id");
     [java] 
     [java]             if (parameterMap.isEmpty()) \{
     [java]               String message =
     [java] ]                "User layout...&gt; but was:&lt;...letRequest =
     [java]               [  PortalUtil.getOriginalServletRequest(
     [java]                     httpServletRequest);
     [java] 
     [java]             Map&lt;String, String[]&gt; parameterMap =
     [java]                 new HashMap&lt;&gt;(
     [java]                 originalHttpServletRequest.getParameterMap());
     [java] 
     [java]             parameterMap.remove("p_l_id");
     [java] 
     [java]             if (parameterMap.isEmpty()) \{
     [java]               String message =
     [java]   ]                "User layout...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 1:01.483 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-38/job/test-portal-source-format/1870//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220728141002230.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220728141002230.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1802485326.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml</pre></details></html>

2022-07-28 21:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1870/">test-portal-source-format#1870</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1870/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/670">liferay-usm#670</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1929395060">[master] ci:test:sf - pei-jung &gt; liferay-usm - PR#670 - 2022-07-28[14:07:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/6038/">publish-testray-report#6038</a><br/></div></div>

2022-07-28 22:14 UTC, pei-jung commented
ci:test:sf

2022-07-28 22:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/2914/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2914/jenkins-report.html">here</a>.</b></p>

2022-07-28 22:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5bd6c053d131da3f345d3c4343860f6ac18bf9c2">5bd6c053d131da3f345d3c4343860f6ac18bf9c2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pei-jung/liferay-portal/tree/LPS-159181">LPS-159181</a><br/>Branch GIT ID: <a href="https://github.com/pei-jung/liferay-portal/commit/8059516a4632650d906df53e6dd38cfa1ae01b2d">8059516a4632650d906df53e6dd38cfa1ae01b2d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2914/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2914/jenkins-report.html">here</a>.</h5></details></html>

2022-07-28 22:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2914/">test-portal-source-format#2914</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2914/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/670">liferay-usm#670</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1929432226">[master] ci:test:sf - pei-jung &gt; liferay-usm - PR#670 - 2022-07-28[15:14:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/10670/">publish-testray-report#10670</a><br/></div></div>

2022-07-28 23:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/4228/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4228/jenkins-report.html">here</a>.</b></p>

2022-07-28 23:21 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0fd9367fc83b9ec1b6e8f5c604bb96a223261fa5">0fd9367fc83b9ec1b6e8f5c604bb96a223261fa5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/46e17c1d34e3a5a75bb6e251317b74a224d5252b">46e17c1d34e3a5a75bb6e251317b74a224d5252b</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1929621882">EE Development Acceptance (master) - 3609 - 2022-07-28[12:39:25]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/4228/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4228/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/4228/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The sender branch SHA could not be found on <strong><a href="https://github.com/liferay-usm/liferay-portal/pull/670">pei-jung/LPS-159181</a></strong>. The sender branch may have been force pushed or deleted after the pull request test was initiated.</p><pre>fatal: Not a valid branch point: 'a0368accb846a1d89a6a87116e85afaefd8f0273'.</pre></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-07-28 23:41 UTC, Sharryxue commented
Relevant test interrupted due to force push, will retrigger the ci:test:relevant.

2022-07-28 23:41 UTC, Sharryxue commented
ci:test:relevant

2022-07-29 00:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/2648/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2648/jenkins-report.html">here</a>.</b></p>

2022-07-29 04:53 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 48 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5bd6c053d131da3f345d3c4343860f6ac18bf9c2">5bd6c053d131da3f345d3c4343860f6ac18bf9c2</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/2648/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2648/jenkins-report.html">here</a>.</b></p>

2022-07-29 05:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/2648/">test-portal-acceptance-pullrequest(master)#2648</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2648/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/670">liferay-usm#670</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1929985474">[master] ci:test:relevant - pei-jung &gt; liferay-usm - PR#670 - 2022-07-28[17:09:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/6060/">publish-testray-report#6060</a><br/></div></div>

2022-07-29 14:09 UTC, drewbrokke requested changes
@pei-jung I think we need to adjust this one. What do you think about this?

1. If the method is GET, disallow using the `p_l_id` parameter.
2. If the method is not GET, allow using the parameter if the user is signed in (we have the `signedIn` variable available to us here).

Thoughts?

2022-07-29 14:09 UTC, drewbrokke commented on portal-impl/src/com/liferay/portal/events/ServicePreAction.java
> +						if (parameterMap.isEmpty()) {
I think with this logic, an attacker could just add an additional dummy query parameter to get around this.

2022-07-29 14:15 UTC, drewbrokke commented
@pei-jung I went ahead and sent https://github.com/liferay-usm/liferay-portal/pull/671 to get CI started in case it's the direction we want to go. LMK what you think.

2022-07-29 16:17 UTC, drewbrokke commented
Looks like Brian merged just merged #672. We'll let the tests complete anyways just in case.

2022-07-29 18:29 UTC, drewbrokke commented
@pei-jung are we ok to close this one?

2022-08-01 12:15 UTC, closed without merging