LPS-162830 Support automatic registration of ConfigurationBeanDeclaration services
liferay-usm/liferay-portal pull request #727
Opened 2022-09-09 22:35 UTC by drewbrokke

This is an update for [LPS-162830](https://issues.liferay.com/browse/LPS-162830).

@izaera and @rotty3000 would you be willing to look this one over and let me know if you see any issues?

/cc @pei-jung

2022-09-09 22:35 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-09-09 22:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/4918/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4918/jenkins-report.html">here</a>.</b></p>

2022-09-09 22:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/3164/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/3164/jenkins-report.html">here</a>.</b></p>

2022-09-09 22:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/de1f94753f627f03c15b14b2478dae91d613778b">de1f94753f627f03c15b14b2478dae91d613778b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/drewbrokke/liferay-portal/tree/LPS-162830-TASK-v0-auto-configuration-bean-declaration">LPS-162830-TASK-v0-auto-configuration-bean-declaration</a><br/>Branch GIT ID: <a href="https://github.com/drewbrokke/liferay-portal/commit/d53eb0aa6ec2a7206bafeddcad88c11f688fe2a6">d53eb0aa6ec2a7206bafeddcad88c11f688fe2a6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/3164/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/3164/jenkins-report.html">here</a>.</h5></details></html>

2022-09-09 22:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/3164/">test-portal-source-format#3164</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/3164/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1972515138">[master] ci:test:sf - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-09[15:36:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/11581/">publish-testray-report#11581</a><br/></div></div>

2022-09-10 01:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 22 out of 26 jobs passed</h3><h3>:x: ci:test:relevant - 37 out of 48 jobs passed in 2 hours 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/de1f94753f627f03c15b14b2478dae91d613778b">de1f94753f627f03c15b14b2478dae91d613778b</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/de1f94753f627f03c15b14b2478dae91d613778b">de1f94753f627f03c15b14b2478dae91d613778b</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1972485172">EE Development Acceptance (master) - 3783 - 2022-09-09[10:17:32]</a></p><details><summary><strong>ci:test:stable - 22 out of 26 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93658/"><strike>functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/230526/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237345/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/82055/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/84111/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200571/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93134/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/193029/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/169772/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/230525/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93226/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/91096/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/230523/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/230522/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/216176/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/91929/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93659/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/169774/"><strike>modules-integration-mysql57-jdk8_stable/0/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/230527/"><strike>modules-integration-mysql57-jdk8_stable/0/1</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/216177/"><strike>modules-integration-mysql57-jdk8_stable/0/2</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/230524/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/193031/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223948/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/91260/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/193030/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223949/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 37 out of 48 jobs PASSED</strong></summary><div><h4>11 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/4918/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/169773/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223950/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237344/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237343/"><strike>functional-smoke-tomcat90-mysql57-jdk11_open/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93658/"><strike>functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/118308/"><strike>functional-smoke-wildfly180-mariadb104-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/83337/"><strike>functional-smoke-wildfly180-mariadb106-jdk8/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/100662/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/87285/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200570/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93225/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a h [...]

2022-09-10 01:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/4918/">test-portal-acceptance-pullrequest(master)#4918</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4918/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1972620461">[master] ci:test:relevant - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-09[15:36:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/11480/">publish-testray-report#11480</a><br/></div></div>

2022-09-12 14:07 UTC, rotty3000 requested changes

2022-09-12 14:07 UTC, rotty3000 commented on modules/apps/portal-configuration/portal-configuration-settings/src/main/java/com/liferay/portal/configuration/settings/internal/settings/definition/ConfigurationBeanDeclarationRegistrar.java
> +		_bundleListener = new BundleListenerImpl();
I would suggest changing from BundleListener to `org.osgi.util.tracker.BundleTracker`. It's easier to use following the semantics of ServiceTracker(Customizer) and covers the "retroactive check" use case in a safer way.

2022-09-14 01:13 UTC, melodywu commented
ci:test:relevant

2022-09-14 02:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/5004/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5004/jenkins-report.html">here</a>.</b></p>

2022-09-14 06:21 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 22 out of 26 jobs passed</h3><h3>:x: ci:test:relevant - 37 out of 48 jobs passed in 4 hours 12 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4acfb3ed1e31069a4acea33367f5d5df63fb8549">4acfb3ed1e31069a4acea33367f5d5df63fb8549</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4acfb3ed1e31069a4acea33367f5d5df63fb8549">4acfb3ed1e31069a4acea33367f5d5df63fb8549</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1975065796">EE Development Acceptance (master) - 3797 - 2022-09-12[20:30:20]</a></p><details><summary><strong>ci:test:stable - 22 out of 26 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221194/"><strike>functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96763/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/83653/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/217371/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94965/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/242963/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/236109/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/120715/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205954/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96084/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94835/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/84905/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/174589/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/242962/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/197312/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205953/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/242965/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/197314/"><strike>modules-integration-mysql57-jdk8_stable/0/0</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227844/"><strike>modules-integration-mysql57-jdk8_stable/0/1</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200799/"><strike>modules-integration-mysql57-jdk8_stable/0/2</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93657/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227842/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221714/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/85281/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205955/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232084/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 37 out of 48 jobs PASSED</strong></summary><div><h4>11 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/5004/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/197313/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205952/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227843/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/174590/"><strike>functional-smoke-tomcat90-mysql57-jdk11_open/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221194/"><strike>functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/85280/"><strike>functional-smoke-wildfly180-mariadb104-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/92731/"><strike>functional-smoke-wildfly180-mariadb106-jdk8/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/201197/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/74895/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221195/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221196/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a  [...]

2022-09-14 06:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/5004/">test-portal-acceptance-pullrequest(master)#5004</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5004/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1976093687">[master] ci:test:relevant - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-13[19:08:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/13114/">publish-testray-report#13114</a><br/></div></div>

2022-09-14 22:59 UTC, drewbrokke commented on modules/apps/portal-configuration/portal-configuration-settings/src/main/java/com/liferay/portal/configuration/settings/internal/settings/definition/ConfigurationBeanDeclarationRegistrar.java
> +		_bundleListener = new BundleListenerImpl();
Ah, that's really nice, thank you for the suggestion @rotty3000!

2022-09-14 22:59 UTC, drewbrokke commented
ci:test:sf

2022-09-14 22:59 UTC, drewbrokke commented
ci:test:relevant

2022-09-14 23:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/4612/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4612/jenkins-report.html">here</a>.</b></p>

2022-09-14 23:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/2480/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/2480/jenkins-report.html">here</a>.</b></p>

2022-09-14 23:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 17 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d3ba0facce600f54e6c8156dbb6df405dad1cde0">d3ba0facce600f54e6c8156dbb6df405dad1cde0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/drewbrokke/liferay-portal/tree/LPS-162830-TASK-v0-auto-configuration-bean-declaration">LPS-162830-TASK-v0-auto-configuration-bean-declaration</a><br/>Branch GIT ID: <a href="https://github.com/drewbrokke/liferay-portal/commit/020d7550a94c21d13da87caeebd4c67b8871b33a">020d7550a94c21d13da87caeebd4c67b8871b33a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/2480/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/2480/jenkins-report.html">here</a>.</h5></details></html>

2022-09-14 23:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/2480/">test-portal-source-format#2480</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/2480/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1977530371">[master] ci:test:sf - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-14[15:59:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/8428/">publish-testray-report#8428</a><br/></div></div>

2022-09-15 01:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/4612/">test-portal-acceptance-pullrequest(master)#4612</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4612/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1977666055">[master] ci:test:relevant - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-14[16:00:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/12140/">publish-testray-report#12140</a><br/></div></div>

2022-09-15 16:57 UTC, drewbrokke commented
ci:test:sf

2022-09-15 16:57 UTC, drewbrokke commented
ci:test:relevant

2022-09-15 16:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/4599/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4599/jenkins-report.html">here</a>.</b></p>

2022-09-15 16:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/3879/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/3879/jenkins-report.html">here</a>.</b></p>

2022-09-15 17:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d3ba0facce600f54e6c8156dbb6df405dad1cde0">d3ba0facce600f54e6c8156dbb6df405dad1cde0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/drewbrokke/liferay-portal/tree/LPS-162830-TASK-v0-auto-configuration-bean-declaration">LPS-162830-TASK-v0-auto-configuration-bean-declaration</a><br/>Branch GIT ID: <a href="https://github.com/drewbrokke/liferay-portal/commit/b5c7dfc094b0f816e433070864fb2d32c5dbeff8">b5c7dfc094b0f816e433070864fb2d32c5dbeff8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/3879/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/3879/jenkins-report.html">here</a>.</h5></details></html>

2022-09-15 17:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/3879/">test-portal-source-format#3879</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/3879/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1978612409">[master] ci:test:sf - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-15[09:57:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/2875/">publish-testray-report#2875</a><br/></div></div>

2022-09-15 19:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 45 out of 48 jobs passed in 2 hours 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d3ba0facce600f54e6c8156dbb6df405dad1cde0">d3ba0facce600f54e6c8156dbb6df405dad1cde0</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d3ba0facce600f54e6c8156dbb6df405dad1cde0">d3ba0facce600f54e6c8156dbb6df405dad1cde0</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1977885389">EE Development Acceptance (master) - 3802 - 2022-09-14[17:38:20]</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 45 out of 48 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/4599/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/231310/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239629/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232741/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225266/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/246482/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209370/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232738/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/246483/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239631/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239630/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200284/"><strike>functional-upgrade-tomcat90-mysql57-jdk8/0/3</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/246481/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/177907/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>lpkg-controller-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/231323/">lpkg-controller-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/204193/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200285/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/246484/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225265/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/246485/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209371/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203982/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/204195/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200286/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232740/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/231308/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/204194/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203981/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/235636/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/231311/">modules-integration-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225267/"><strike>modules-integration-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/235637/">modules-integration-mysql57-jdk8/0/2</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239634/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209372/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203983/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232737/">modules-semantic-versioning-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209369/">modules-unit-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239633/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>modules-unit-project-templates-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232739/">modules-unit-project-templates-jdk8/0/0</a></li><li><a [...]

2022-09-15 19:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/4599/">test-portal-acceptance-pullrequest(master)#4599</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4599/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1978842827">[master] ci:test:relevant - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-15[09:58:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/11734/">publish-testray-report#11734</a><br/></div></div>

2022-09-15 19:53 UTC, drewbrokke commented
@patriciajeanperez is this failure real? Would it be worth re-running `relevant`?

2022-09-15 21:52 UTC, drewbrokke commented
ci:test:relevant

2022-09-15 21:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/5818/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5818/jenkins-report.html">here</a>.</b></p>

2022-09-16 00:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 46 out of 48 jobs passed in 2 hours 32 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d3ba0facce600f54e6c8156dbb6df405dad1cde0">d3ba0facce600f54e6c8156dbb6df405dad1cde0</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d3ba0facce600f54e6c8156dbb6df405dad1cde0">d3ba0facce600f54e6c8156dbb6df405dad1cde0</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1977885389">EE Development Acceptance (master) - 3802 - 2022-09-14[17:38:20]</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 46 out of 48 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/5818/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225089/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247023/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/231790/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247027/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225775/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/240141/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225776/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221301/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/236127/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/236126/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209881/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/178393/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221300/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>lpkg-controller-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247024/">lpkg-controller-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/240140/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/236128/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209883/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221303/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/178392/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221304/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209885/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225780/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/231791/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233235/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221302/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209884/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247022/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/236129/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233237/">modules-integration-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209886/"><strike>modules-integration-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247028/">modules-integration-mysql57-jdk8/0/2</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/240143/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/236130/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225774/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209880/">modules-semantic-versioning-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209882/">modules-unit-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/240142/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>modules-unit-project-templates-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247026/">modules-unit-project-templates-jdk8/0/0</a></li><li><a href="https://te [...]

2022-09-16 00:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/5818/">test-portal-acceptance-pullrequest(master)#5818</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5818/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1979199359">[master] ci:test:relevant - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-15[14:53:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/15301/">publish-testray-report#15301</a><br/></div></div>

2022-09-16 15:53 UTC, drewbrokke commented
ci:test:relevant

2022-09-16 16:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/4423/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4423/jenkins-report.html">here</a>.</b></p>

2022-09-16 17:40 UTC, epark18 commented
Hi @drewbrokke. I believe your changes to the _SettingsLocatorHelperImpl.java_ file is the cause of the relevant failures according to the job summary. It looks like the changes are causing the tests to run longer and the build is timing out. 

There was an issue with loggers in Brian's upstream recently. Details are in this [thread](https://liferay.slack.com/archives/CLCD3DQLF/p1663051635929259). Shuyang mentioned a problem with logs so maybe this could be helpful.

2022-09-16 19:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 26 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 44 out of 48 jobs passed in 2 hours 35 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3805">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1287401_4423</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dea6d68e54edb40fcfaad6631eb45fda041f0b47">dea6d68e54edb40fcfaad6631eb45fda041f0b47</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d3ba0facce600f54e6c8156dbb6df405dad1cde0">d3ba0facce600f54e6c8156dbb6df405dad1cde0</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1977885389">EE Development Acceptance (master) - 3802 - 2022-09-14[17:38:20]</a></p><details><summary><strong>ci:test:stable - 26 out of 27 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237776/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227447/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248862/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222937/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227450/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205979/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241883/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248860/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227451/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233446/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205981/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179983/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/202223/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237775/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222934/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205980/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179982/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222935/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233447/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241886/"><strike>modules-integration-mysql57-jdk8_stable/0/1</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205982/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248861/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227452/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227446/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241884/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222936/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237770/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>26 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 44 out of 48 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/4423/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237776/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179978/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/202224/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241885/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227447/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237774/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237772/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222933/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1- [...]

2022-09-16 19:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/4423/">test-portal-acceptance-pullrequest(master)#4423</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4423/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1980859507">[master] ci:test:relevant - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-16[09:48:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/10974/">publish-testray-report#10974</a><br/></div></div>

2022-09-16 20:42 UTC, drewbrokke commented
ci:reevaluate:1287401_4423

2022-09-16 20:42 UTC, liferay-continuous-integration commented
CI is reevaluating the build with build ID: `1287401_4423` against the latest valid upstream results.

2022-09-16 20:44 UTC, liferay-continuous-integration commented
<html><p>Previous <code>ci:test:relevant</code><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/4423">build</a> was unsuccessfully <a href="https://test-1-25.liferay.com/job/test-portal-evaluate-pullrequest/167/">reevaluated</a> against more recent upstream results.</p><h3>:x: ci:test:stable - 24 out of 25 jobs passed</h3><h3>:x: ci:test:relevant - 44 out of 48 jobs passed in 2 hours 36 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3805">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1287401_4423</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dea6d68e54edb40fcfaad6631eb45fda041f0b47">dea6d68e54edb40fcfaad6631eb45fda041f0b47</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f2471ae7850b6937f6e662b274f0901413151dc8">f2471ae7850b6937f6e662b274f0901413151dc8</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1980845150">EE Development Acceptance (master) - 3804 - 2022-09-16[07:40:35]</a></p><details><summary><strong>ci:test:stable - 24 out of 25 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237776/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227447/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227450/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205979/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241883/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248860/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227451/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233446/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205981/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179983/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/202223/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237775/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222934/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205980/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179982/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222935/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233447/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241886/"><strike>modules-integration-mysql57-jdk8_stable/0/1</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205982/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248861/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227452/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227446/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241884/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222936/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237770/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 44 out of 48 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/4423/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237776/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179978/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/202224/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241885/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227447/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237774/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237772/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222933/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205978/">functional-upgrade-tom [...]

2022-09-20 14:31 UTC, drewbrokke commented
ci:reevaluate:1287401_4423

2022-09-20 14:35 UTC, liferay-continuous-integration commented
<html><p>Previous <code>ci:test:relevant</code><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/4423">build</a> was unsuccessfully <a href="https://test-1-37.liferay.com/job/test-portal-evaluate-pullrequest/153/">reevaluated</a> against more recent upstream results.</p><h3>:x: ci:test:stable - 24 out of 25 jobs passed</h3><h3>:x: ci:test:relevant - 44 out of 48 jobs passed in 2 hours 36 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dea6d68e54edb40fcfaad6631eb45fda041f0b47">dea6d68e54edb40fcfaad6631eb45fda041f0b47</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dea6d68e54edb40fcfaad6631eb45fda041f0b47">dea6d68e54edb40fcfaad6631eb45fda041f0b47</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1981059170">EE Development Acceptance (master) - 3805 - 2022-09-16[10:11:00]</a></p><details><summary><strong>ci:test:stable - 24 out of 25 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237776/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227447/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227450/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205979/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241883/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248860/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227451/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233446/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205981/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179983/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/202223/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237775/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222934/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205980/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179982/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222935/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233447/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241886/"><strike>modules-integration-mysql57-jdk8_stable/0/1</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205982/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248861/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227452/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227446/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241884/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222936/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237770/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 44 out of 48 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/4423/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237776/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179978/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/202224/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241885/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227447/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237774/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237772/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222933/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205978/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179980/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227449/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://t [...]

2022-09-20 17:36 UTC, drewbrokke commented
ci:test:relevant

2022-09-20 17:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/5105/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5105/jenkins-report.html">here</a>.</b></p>

2022-09-20 21:14 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 26 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 45 out of 48 jobs passed in 3 hours 36 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3818">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1317401_5105</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f000b61ffabb63a922c95972ab80c5c56bdc6926">f000b61ffabb63a922c95972ab80c5c56bdc6926</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/57a60da440e82afe14a7aea0c4075b33bae5b051">57a60da440e82afe14a7aea0c4075b33bae5b051</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1984048289">EE Development Acceptance (master) - 3815 - 2022-09-20[02:38:15]</a></p><details><summary><strong>ci:test:stable - 26 out of 27 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232275/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239151/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/228498/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/217480/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207092/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89220/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211055/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/77260/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/255264/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/255265/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/99589/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/255266/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/88478/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/255263/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/87800/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/88893/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207093/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/97781/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/255267/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211070/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239154/"><strike>modules-integration-mysql57-jdk8_stable/0/2</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/99792/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211069/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207091/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96460/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/217479/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/88892/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>26 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 45 out of 48 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/5105/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232275/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/97780/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/243666/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/243665/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239151/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239153/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/101455/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/228497/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job [...]

2022-09-20 21:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/5105/">test-portal-acceptance-pullrequest(master)#5105</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5105/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1984534681">[master] ci:test:relevant - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-20[10:37:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/13317/">publish-testray-report#13317</a><br/></div></div>

2022-09-20 22:46 UTC, drewbrokke commented
ci:test:relevant

2022-09-20 22:47 UTC, drewbrokke commented
ci:test:sf

2022-09-20 22:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/3092/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3092/jenkins-report.html">here</a>.</b></p>

2022-09-20 23:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 18 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d234de8e6955b8b4d71ec38a46d7dea4e009e624">d234de8e6955b8b4d71ec38a46d7dea4e009e624</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/drewbrokke/liferay-portal/tree/LPS-162830-TASK-v0-auto-configuration-bean-declaration">LPS-162830-TASK-v0-auto-configuration-bean-declaration</a><br/>Branch GIT ID: <a href="https://github.com/drewbrokke/liferay-portal/commit/464d6b60df8bd6089e90c6678426c4bcefc3cc45">464d6b60df8bd6089e90c6678426c4bcefc3cc45</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3092/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3092/jenkins-report.html">here</a>.</h5></details></html>

2022-09-20 23:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3092/">test-portal-source-format#3092</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3092/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1984742739">[master] ci:test:sf - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-20[15:47:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/12066/">publish-testray-report#12066</a><br/></div></div>

2022-09-20 23:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/2651/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2651/jenkins-report.html">here</a>.</b></p>

2022-09-20 23:17 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d234de8e6955b8b4d71ec38a46d7dea4e009e624">d234de8e6955b8b4d71ec38a46d7dea4e009e624</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38f33f11d98899224ba3b4710336accf9f1ff91b">38f33f11d98899224ba3b4710336accf9f1ff91b</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1984442993">EE Development Acceptance (master) - 3817 - 2022-09-20[07:43:32]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/2651/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2651/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/2651/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The sender branch SHA could not be found on <strong><a href="https://github.com/liferay-usm/liferay-portal/pull/727">drewbrokke/LPS-162830-TASK-v0-auto-configuration-bean-declaration</a></strong>. The sender branch may have been force pushed or deleted after the pull request test was initiated.</p><pre>fatal: Not a valid branch point: '7f7a46a087a4e4cd88d72e88bd272364c798503e'.</pre></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-09-20 23:24 UTC, drewbrokke commented
ci:test:relevant

2022-09-20 23:24 UTC, drewbrokke commented
ci:test:sf

2022-09-20 23:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/3094/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3094/jenkins-report.html">here</a>.</b></p>

2022-09-20 23:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4671/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4671/jenkins-report.html">here</a>.</b></p>

2022-09-20 23:41 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 16 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d234de8e6955b8b4d71ec38a46d7dea4e009e624">d234de8e6955b8b4d71ec38a46d7dea4e009e624</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/drewbrokke/liferay-portal/tree/LPS-162830-TASK-v0-auto-configuration-bean-declaration">LPS-162830-TASK-v0-auto-configuration-bean-declaration</a><br/>Branch GIT ID: <a href="https://github.com/drewbrokke/liferay-portal/commit/464d6b60df8bd6089e90c6678426c4bcefc3cc45">464d6b60df8bd6089e90c6678426c4bcefc3cc45</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3094/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3094/jenkins-report.html">here</a>.</h5></details></html>

2022-09-20 23:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3094/">test-portal-source-format#3094</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3094/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1984870115">[master] ci:test:sf - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-20[16:25:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/12070/">publish-testray-report#12070</a><br/></div></div>

2022-09-21 00:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 47 out of 48 jobs passed in 1 hour 18 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d234de8e6955b8b4d71ec38a46d7dea4e009e624">d234de8e6955b8b4d71ec38a46d7dea4e009e624</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f000b61ffabb63a922c95972ab80c5c56bdc6926">f000b61ffabb63a922c95972ab80c5c56bdc6926</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1984778212">EE Development Acceptance (master) - 3818 - 2022-09-20[10:09:02]</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 46 out of 48 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4671/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/244298/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207606/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211579/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241490/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241486/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229087/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239759/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207608/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185920/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207607/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241487/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207611/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232861/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>lpkg-controller-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185919/">lpkg-controller-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239760/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207610/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232862/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218096/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232863/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229088/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248607/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211653/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207609/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185922/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211580/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239761/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241489/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248606/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/248608/">modules-integration-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229089/">modules-integration-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233951/"><strike>modules-integration-mysql57-jdk8/0/2</strike></a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185923/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/255921/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218098/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185918/">modules-semantic-versioning-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218095/">modules-unit-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233950/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>modules-unit-project-templates-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185921/">modules-unit-project-templates-jdk8/0/0</a></li><li><a hr [...]

2022-09-21 00:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4671/">test-portal-acceptance-pullrequest(master)#4671</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4671/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1984902802">[master] ci:test:relevant - drewbrokke &gt; liferay-usm - PR#727 - 2022-09-20[16:36:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/11729/">publish-testray-report#11729</a><br/></div></div>

2022-10-17 09:04 UTC, Sharryxue commented
ci:test:system

2022-10-17 09:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>system</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/5461/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5461/jenkins-report.html">here</a>.</b></p>

2022-10-17 11:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:system - 36 out of 38 jobs passed in 1 hour 57 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6bc0d3869ec99b602aeecaa51f2e231c169570d7">6bc0d3869ec99b602aeecaa51f2e231c169570d7</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6bc0d3869ec99b602aeecaa51f2e231c169570d7">6bc0d3869ec99b602aeecaa51f2e231c169570d7</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2007721180">EE Development Acceptance (master) - 3909 - 2022-10-16[05:06:26]</a></p><details><summary><strong>ci:test:system - 36 out of 38 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/5461/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274333/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109697/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241477/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266023/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241478/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266024/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274332/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/294583/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/294584/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/62448/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/110517/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/284891/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109400/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/103984/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280212/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/113065/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266020/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269647/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266022/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280213/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/294582/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266025/">functional-tomcat90-mysql57-jdk8/0/20</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109102/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/284893/">modules-integration-mysql57-jdk8/0/0</a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109399/">modules-semantic-versioning-jdk8/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109398/">modules-semantic-versioning-jdk8/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/266021/">modules-semantic-versioning-jdk8/0/2</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/91234/">modules-semantic-versioning-jdk8/0/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/284892/">modules-semantic-versioning-jdk8/0/4</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109696/">modules-semantic-versioning-jdk8/0/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/111221/">modules-semantic-versioning-jdk8/0/6</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/107002/">modules-semantic-versioning-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280211/">modules-semantic-versioning-jdk8/0/8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109695/">modules-semantic-versioning-jdk8/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280210/">modules-semantic-versioning-jdk8/0/10</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/277289/">modules-unit-jdk8/0/0</a></li></ul></li><li>semantic-versioning-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241479/">semantic-versioning-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>36 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5461/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241477//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/241477//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_InstanceSettings_CanAddContactInformationInInstanceConfiguration_">LocalFile.InstanceSettings#CanAddContactInformationInInstanceConfiguration</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-10/test-1-31/test-portal-acceptance-pullreq [...]

2022-10-17 11:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/5461/">test-portal-acceptance-pullrequest(master)#5461</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5461/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>system<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-usm/liferay-portal/pull/727">liferay-usm#727</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2008166518">[master] ci:test:system - drewbrokke &gt; liferay-usm - PR#727 - 2022-10-17[02:40:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/14172/">publish-testray-report#14172</a><br/></div></div>

2022-10-17 12:11 UTC, Sharryxue commented
No related issue found in ci:test:system.

2022-11-04 13:20 UTC, drewbrokke commented
Superseded by https://github.com/dantewang/liferay-portal/pull/2269

2022-11-04 13:20 UTC, closed without merging