Add new country's states to the address API
liferay-usm/liferay-portal pull request #960
Opened 2023-02-06 13:40 UTC by ytuik

As discussed in this [thread](https://liferay.slack.com/archives/C5E1CRLJY/p1675431115163509), this PR adds some new regions for the Address API.

I used as main reference the file bellow and the [Wikipedia Link](https://commons.wikimedia.org/wiki/Atlas_of_first-level_administrative_divisions) with the adminstrative division
[Country and State drop downs (1).xlsx](https://github.com/liferay-usm/liferay-portal/files/10663550/Country.and.State.drop.downs.1.xlsx)

2023-02-06 21:49 UTC, drewbrokke requested changes
Thank you for sending this change, @ytuik! There are a few places where we need to adjust and double-check. Please see my inline comments.

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/AE.json
> +		"name": "Ra#s al-Chaima",
This `#` does not seem correct. It's not present in Wikipedia.

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/BE.json
> +		"name": "Brabant (Walloon)",
Seems like the `Brabant` provinces can also be written as "Flemish Brabant" and "Walloon Brabant". It seems a bit more readable to put Brabant last. Thoughts?

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/NZ.json
> +		"name": "Hawke´s Bay",
I think this needs to be a `'` instead of a `´`.

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/PT.json
> +		"name": "Pinhal Interior N.",
Here it's `N.`, but below it's `Norte`. I think we should stick with spelling it out as `Norte`.

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/SE.json
> +		"name": "Vaesternorrland Cnty",
Cnty > County

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/SE.json
> +		"name": "Oestergoetland Cnty",
Cnty > County

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/SE.json
> +]
Do these all need the `County` suffix? On Wikipedia they are just listed by their names. Is it generally included like this?

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/SE.json
> +		"name": "Vaestra Goetaland C.",
C. > County

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/TW.json
> +		"name": "T´ai-pei",
Same as above, change `´` to `'`

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/UA.json
> +]
These Ukranian regions seem to differ pretty heavily from what is listed on Wikipedia. Can you please double-check these entries?

2023-02-06 21:49 UTC, drewbrokke commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/ZA.json
> +		"name": "Kwazulu/Natal",
I think this should be hyphenated and capitalized differently.

https://en.wikipedia.org/wiki/KwaZulu-Natal

2023-02-07 22:41 UTC, ytuik commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/AE.json
> +		"name": "Ra#s al-Chaima",
Those # are some special characters that i let pass, i'll fix them

2023-02-07 23:00 UTC, ytuik commented on modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies/regions/SE.json
> +]
In these cases yes because most of it shares the same name as it's capitals

2023-02-07 23:26 UTC, ytuik commented
It was really with some inconsistencies but it's all fixed

2023-02-27 16:16 UTC, ytuik commented
ci:test:sf

2023-04-25 19:20 UTC, brunofalc commented
ci:close

2023-04-25 19:20 UTC, closed without merging